# Generated by Django 5.2.7 on 2026-01-26 00:15

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossilite_rag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
            ],
            options={
                'db_table': 'college_application_documents',
            },
        ),
        # Handle Document -> CDSDocument rename
        # Use SeparateDatabaseAndState to conditionally rename table but always update Django state
        migrations.SeparateDatabaseAndState(
            # Database operations: rename table if it exists, or create it if it doesn't
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF EXISTS (
                                SELECT FROM information_schema.tables 
                                WHERE table_schema = 'public' 
                                AND table_name = 'documents'
                            ) THEN
                                -- Table exists, rename it
                                ALTER TABLE documents RENAME TO cds_documents;
                            ELSIF NOT EXISTS (
                                SELECT FROM information_schema.tables 
                                WHERE table_schema = 'public' 
                                AND table_name = 'cds_documents'
                            ) THEN
                                -- Table doesn't exist, create it with the new name
                                -- Match Django's exact structure from 0001_initial
                                CREATE TABLE cds_documents (
                                    id BIGSERIAL NOT NULL PRIMARY KEY,
                                    title VARCHAR(255) NOT NULL,
                                    content TEXT NOT NULL,
                                    embedding vector(1024)
                                );
                            END IF;
                        END $$;
                    """,
                    reverse_sql="""
                        DO $$
                        BEGIN
                            IF EXISTS (
                                SELECT FROM information_schema.tables 
                                WHERE table_schema = 'public' 
                                AND table_name = 'cds_documents'
                            ) THEN
                                ALTER TABLE cds_documents RENAME TO documents;
                            END IF;
                        END $$;
                    """,
                ),
            ],
            # State operations: always update Django's model state
            state_operations=[
                migrations.RenameModel(
                    old_name='Document',
                    new_name='CDSDocument',
                ),
                migrations.AlterModelTable(
                    name='cdsdocument',
                    table='cds_documents',
                ),
            ],
        ),
    ]
