# Generated by Django 5.2.7 on 2025-12-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('MS', 'Middle School'), ('HS', 'High School'), ('CC', 'Community College'), ('UN', 'University')], max_length=255),
        ),
    ]
